# Lab 12-0 RNN basic
- learning 'hello'

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential, Model

### Preparing dataset

In [2]:
# One hot encoding for each character in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

### One cell: 4(input_dim) in 2(hidden_size)

In [3]:
# One cell RNN input_dim(4) -> output_dim(2)
x_data = np.array([[h]], dtype=np.float32)

hidden_size = 2
cell = layers.SimpleRNNCell(units=hidden_size) # creating SimpleRNNCell
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
# analogue to tf.nn.dynamic_rnn
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.15236975  0.2098447 ]]], shape: (1, 1, 2)
states: [[-0.15236975  0.2098447 ]], shape: (1, 2)


In [4]:
# equivalent to above case
# layers.simpleRNNCell + layers.RNN
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)

outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[0.6621859 0.534178 ]]], shape: (1, 1, 2)
states: [[0.6621859 0.534178 ]], shape: (1, 2)


### Unfolding to N sequences
- `keras.layers.SimpleRNN`
    - `return_sequences`: **Boolean**. Whether to return the last output in the output sequence, or the full sequence. Default: False.
    - `return_state` : **Boolean**. Whether to return the last state in addition to the output. Default: False

In [5]:
# One cell RNN input_dim(4) -> output_dim(2), sequence: 5
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)

hidden_size = 2
rnn = layers.SimpleRNN(units=2, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4)
outputs: [[[ 0.7007115  -0.46957633]
  [ 0.23233579 -0.1601763 ]
  [ 0.485673    0.68913174]
  [ 0.30783862  0.936254  ]
  [ 0.18348669  0.9550434 ]]], shape: (1, 5, 2)
states: [[0.18348669 0.9550434 ]], shape: (1, 2)


### Batching input

In [6]:
# Onecell RNN input_dim(4) -> output_dim(2), sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2
rnn = layers.SimpleRNN(units=2, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)


print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4)
outputs: [[[ 0.5046142   0.67641485]
  [-0.60148877 -0.13016753]
  [ 0.16202661 -0.92005575]
  [ 0.71393704 -0.6468965 ]
  [ 0.917318    0.5721257 ]]

 [[ 0.01615908 -0.5259297 ]
  [ 0.90558624 -0.05404606]
  [-0.02309094 -0.09171242]
  [ 0.08246348 -0.7679767 ]
  [ 0.6347556  -0.6964931 ]]

 [[-0.01050863 -0.761208  ]
  [ 0.63480055 -0.7414424 ]
  [ 0.61004704  0.10265781]
  [-0.13026424  0.01636061]
  [-0.01726003 -0.811086  ]]], shape: (3, 5, 2)
states: [[ 0.917318    0.5721257 ]
 [ 0.6347556  -0.6964931 ]
 [-0.01726003 -0.811086  ]], shape: (3, 2)
