In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

tf.random.set_seed(777) # for reproducibility

2.2.0


In [2]:
# 4 features and 8 data
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# convert into numpy and float format
x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32)

In [3]:
nb_classes = 3 # num classes

print(x_data.shape)
print(y_data.shape)

(8, 4)
(8, 3)


In [4]:
# Weight and bias setting
W = tf.Variable(tf.random.normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random.normal([nb_classes]), name='bias')

variables = [W, b]

print(W, b)

<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.7706481 ,  0.37335402, -0.05576323],
       [ 0.00358377, -0.5898363 ,  1.5702795 ],
       [ 0.2460895 , -0.09918973,  1.4418385 ],
       [ 0.3200988 ,  0.526784  , -0.7703731 ]], dtype=float32)> <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([-1.3080608 , -0.13253094,  0.5513761 ], dtype=float32)>


In [5]:
def hypothesis(X):
    return tf.nn.softmax(tf.matmul(X, W) + b)

In [6]:
sample_db = [[8, 2, 1, 4]]
sample_db = np.asarray(sample_db, dtype=np.float32)

In [7]:
def cost_fn(X, Y):
    logits = hypothesis(X)
    cost = -tf.reduce_sum(Y * tf.math.log(logits), axis=1)
    cost_mean = tf.reduce_mean(cost)
    return cost_mean


def grad_fn(X, Y):
    with tf.GradientTape() as tape:
        cost = cost_fn(X, Y)
        grads = tape.gradient(cost, variables)
        return grads
    
def fit(X, Y, epochs=2000, verbose=100):
    optimizer = tf.keras.optimizers.SGD(learning_rate=0.1)
    for i in range(epochs):
        grads = grad_fn(X, Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i == 0) | ((i+1) % verbose == 0):
            print('Loss at epoch {}: {:0.5f}'.format(i+1, cost_fn(X, Y).numpy()))

fit(x_data, y_data)

Loss at epoch 1: 2.84942
Loss at epoch 100: 0.68415
Loss at epoch 200: 0.61381
Loss at epoch 300: 0.55820
Loss at epoch 400: 0.50831
Loss at epoch 500: 0.46106
Loss at epoch 600: 0.41507
Loss at epoch 700: 0.36964
Loss at epoch 800: 0.32453
Loss at epoch 900: 0.28072
Loss at epoch 1000: 0.24675
Loss at epoch 1100: 0.23280
Loss at epoch 1200: 0.22164
Loss at epoch 1300: 0.21148
Loss at epoch 1400: 0.20216
Loss at epoch 1500: 0.19361
Loss at epoch 1600: 0.18571
Loss at epoch 1700: 0.17841
Loss at epoch 1800: 0.17165
Loss at epoch 1900: 0.16535
Loss at epoch 2000: 0.15948


In [8]:
# Prediction
sample_data = [[2, 1, 3, 2]] # answer [[0, 0, 1]]
sample_data = np.asarray(sample_data, dtype=np.float32)

a = hypothesis(sample_data)

print(a)
print(tf.argmax(a, 1))

tf.Tensor([[0.00112886 0.08154677 0.9173244 ]], shape=(1, 3), dtype=float32)
tf.Tensor([2], shape=(1,), dtype=int64)


In [9]:
a = hypothesis(x_data)

print(a)

print('comparison between prediction and result')
print('hypothesis(x_data):', tf.argmax(a, 1)) # argmax : Data 중 가장 큰 값의 index 반환
print('            y_data:', tf.argmax(y_data, 1))

tf.Tensor(
[[2.1975975e-06 1.2331199e-03 9.9876475e-01]
 [1.1288556e-03 8.1546769e-02 9.1732442e-01]
 [2.2205620e-07 1.6418636e-01 8.3581340e-01]
 [6.3921821e-06 8.5045445e-01 1.4953916e-01]
 [2.6150796e-01 7.2644740e-01 1.2044553e-02]
 [1.3783275e-01 8.6213976e-01 2.7417653e-05]
 [7.4242103e-01 2.5754195e-01 3.6978705e-05]
 [9.2197531e-01 7.8024112e-02 6.0006198e-07]], shape=(8, 3), dtype=float32)
comparison between prediction and result
x_data with hypothesis tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
y_data tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
